version: '3.8'

services:
  ads-api:
    build: ./
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_USER=admin
      - POSTGRES_DB=postingAds
    ports:
      - 5436:5432


