http:
  host: "localhost"
  port: "8000"
  maxHeaderBytes: "1"
  readTimeout: "10s"
  writeTimeout: "10s"

db:
  postgres:
    host: "localhost"
    port: "5436"
    username: "artem"
    dbName: "postingAds"
    SSLMode: "disable"

auth:
  accessTokenTTL: "30m"
  refreshTokenTTL: "60m"
