http:
  host: "localhost"
  port: "8000"
  maxHeaderBytes: "1"
  readTimeout: "10s"
  writeTimeout: "10s"

db:
  postgres:
    host: "db"
    port: "5432"
    username: "admin"
    dbName: "postingAds"
    SSLMode: "disable"
